logging:
  file:
    name: logs/authentication.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    com.ktds.devopshelper.authentication: debug



# DB
spring:
  config:
    import:
      - classpath:/config/datasource-local.yml

server:
  port: 8900

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka