#로그설
logging:
  file:
    name: logs/api-local.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    com.ktds.devopshelper.faqnaservice: debug
   
# DB
spring:
  config:
    import:
      - classpath:/config/datasource-local.yml

#포트
server:
  port: 0
  
#spring doc swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

token:
  expiration_time: 86400000
  secret: SECU100

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
    # instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone:  http://localhost:8761/eureka